[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/signup.html"
  status = 200

[[redirects]]
  from = "/careers"
  to = "/careers.html"
  status = 200

[[redirects]]
  from = "/security"
  to = "/security.html"
  status = 200
